apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesboost-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesboost-frontend
  template:
    metadata:
      labels:
        app: salesboost-frontend
    spec:
      containers:
        - name: salesboost-frontend
          image: ckato9173/salesboost-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: salesboost-frontend
spec:
  selector:
    app: salesboost-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
